
import random
import csv
import math
from collections import Counter

# === Общий supply ===
total_supply = 4818

# === Вставь реальные подарки (до 10) ===
# Формат: ("Model", "Background", "Pattern")
real_gifts = [    ('Mantis', 'Mint Green', 'High Hat'),    ('Market Rally', 'Gunmetal', 'Ram of Amun'),    ('Diamond', 'English Violet', 'Trophy'),    ('Pug Royale', 'Amber', 'Elephant'),    ('Rose Gold', 'Shamrock Green', 'Doctor Hat'),    ('Rainbow Pills', 'Rosewood', 'Elf Hat'),    ('Ouroboros', 'Caramel', 'Ushanka'),    ('Mantis', 'Fandango', 'Flower'),    ('Interstellar', 'Dark Green', 'Wagasa'),    ('Hologram', 'Ranger Green', 'Sauron'),]
# === Списки всех атрибутов с их процентами ===
models = [
    ("Diamond", 0.5),
    ("Gold Rush", 0.5),
    ("Interstellar", 0.5),
    ("Mystic Copper", 0.5),
    ("Blue Velvet", 1),
    ("Hypno Kaa", 1),
    ("Aqua Ring", 1.5),
    ("Black Panther", 1.5),
    ("Blue Dolphin", 1.5),
    ("Carrot Bunny", 1.5),
    ("Cat Person", 1.5),
    ("Crypto Gem", 1.5),
    ("Duck Amulet", 1.5),
    ("Hachikō", 1.5),
    ("Heavy Metal", 1.5),
    ("Mario Pipe", 1.5),
    ("Market Rally", 1.5),
    ("Moon Cat", 1.5),
    ("Ocelot", 1.5),
    ("Ouroboros", 1.5),
    ("Pearl Glam", 1.5),
    ("Pepe Band", 1.5),
    ("Resistance", 1.5),
    ("Scorpio", 1.5),
    ("Succubus", 1.5),
    ("Tesla Coil", 1.5),
    ("Candle Wax", 2),
    ("Monster Eye", 2),
    ("Nuclear Silo", 2),
    ("Pencil", 2),
    ("Pug Royale", 2),
    ("Rainbow Pills", 2),
    ("Explosive", 2.5),
    ("Hologram", 2.5),
    ("Needle", 2.5),
    ("Neon Tube", 2.5),
    ("Rusty Nail", 2.5),
    ("Vague Dream", 2.5),
    ("X-Ray", 2.5),
    ("Firebronze", 3),
    ("Jade Serpent", 3),
    ("Mantis", 3),
    ("Pure Amber", 3),
    ("Argent", 3.5),
    ("Red Fang", 3.5),
    ("Rose Gold", 3.5),
    ("Rose Thorn", 3.5),
    ("Shadow", 3.5),
    ("Skyline", 3.5),
    ("Ultramarine", 3.5)
]

backgrounds = [
    ("Cobalt Blue", 1),
    ("Mexican Pink", 1),
    ("Steel Grey", 1),
    ("Indigo Dye", 1),
    ("Electric Indigo", 1),
    ("Ranger Green", 1),
    ("Shamrock Green", 1),
    ("French Violet", 1),
    ("Pacific Green", 1),
    ("Pistachio", 1),
    ("Roman Silver", 1),
    ("Sky Blue", 1),
    ("Dark Lilac", 1),
    ("Neon Blue", 1),
    ("Desert Sand", 1),
    ("Coral Red", 1),
    ("Orange", 1),
    ("Seal Brown", 1),
    ("Camo Green", 1),
    ("Tomato", 1),
    ("Aquamarine", 1),
    ("Pacific Cyan", 1),
    ("Hunter Green", 1.2),
    ("Moonstone", 1.2),
    ("Khaki Green", 1.2),
    ("Ivory White", 1.2),
    ("Cyberpunk", 1.2),
    ("Pure Gold", 1.2),
    ("Caramel", 1.2),
    ("Persimmon", 1.2),
    ("Malachite", 1.2),
    ("Fire Engine", 1.2),
    ("Chocolate", 1.2),
    ("Rifle Green", 1.2),
    ("Onyx Black", 1.2),
    ("Battleship Grey", 1.2),
    ("Rosewood", 1.2),
    ("Amber", 1.2),
    ("Lavender", 1.2),
    ("Navy Blue", 1.2),
    ("Strawberry", 1.2),
    ("Mystic Pearl", 1.2),
    ("Electric Purple", 1.2),
    ("Chestnut", 1.2),
    ("Gunmetal", 1.2),
    ("Platinum", 1.2),
    ("Marine Blue", 1.2),
    ("Pine Green", 1.2),
    ("Turquoise", 1.2),
    ("Feldgrau", 1.2),
    ("Gunship Green", 1.2),
    ("French Blue", 1.2),
    ("Mustard", 1.5),
    ("Black", 1.5),
    ("Old Gold", 1.5),
    ("Carrot Juice", 1.5),
    ("Tactical Pine", 1.5),
    ("Raspberry", 1.5),
    ("Midnight Blue", 1.5),
    ("Deep Cyan", 1.5),
    ("Silver Blue", 1.5),
    ("Celtic Blue", 1.5),
    ("Copper", 1.5),
    ("Emerald", 1.5),
    ("Light Olive", 1.5),
    ("Purple", 1.5),
    ("Fandango", 1.5),
    ("Mint Green", 1.5),
    ("Burgundy", 1.5),
    ("English Violet", 1.5),
    ("Dark Green", 1.5),
    ("Carmine", 1.5),
    ("Azure Blue", 1.5),
    ("Sapphire", 1.5),
    ("Burnt Sienna", 1.5),
    ("Jade Green", 1.5),
    ("Cappuccino", 1.5),
    ("Satin Gold", 1.5),
    ("Grape", 1.5),
    ("Lemongrass", 1.5)
]

patterns = [
    ("Bee", 0.2),
    ("Robin Hood", 0.2),
    ("All- Seeing Eye", 0.2),
    ("Mayan Moth", 0.2),
    ("Love Letter", 0.2),
    ("Gamepad", 0.2),
    ("Viking", 0.2),
    ("Bowler Hat", 0.2),
    ("French Fries", 0.2),
    ("Sumerian Bird", 0.2),
    ("Hersir", 0.2),
    ("Ouroboros", 0.2),
    ("Nordic Wolf", 0.2),
    ("Golden Scarab", 0.2),
    ("Aztec Falcon", 0.2),
    ("Sword", 0.2),
    ("Bastet", 0.2),
    ("Wreath", 0.2),
    ("Tiki Mask", 0.2),
    ("Twin Koi", 0.2),
    ("Chili", 0.2),
    ("Blood Drop", 0.2),
    ("Turkey", 0.2),
    ("Mushroom", 0.2),
    ("The Eye", 0.2),
    ("Double Axe", 0.2),
    ("Cash", 0.2),
    ("Anubis", 0.2),
    ("Clubs", 0.2),
    ("Unicorn Head", 0.2),
    ("Ice Cream", 0.2),
    ("Jellyfish", 0.2),
    ("Bonsai", 0.2),
    ("Peace Dove", 0.2),
    ("Sword Fight", 0.2),
    ("Hamburger", 0.2),
    ("Grenade", 0.2),
    ("Morgenstern", 0.2),
    ("Tsunami", 0.2),
    ("Flipper", 0.2),
    ("Calm Wolf", 0.2),
    ("Chest", 0.2),
    ("Eye of Horus", 0.2),
    ("Horn", 0.2),
    ("Bicorne", 0.2),
    ("Galaxy", 0.2),
    ("Gem", 0.2),
    ("Bug", 0.2),
    ("Flat Cap", 0.2),
    ("Star", 0.2),
    ("Bamboo", 0.2),
    ("Grape", 0.2),
    ("Narcissus", 0.2),
    ("Rhino Warrior", 0.2),
    ("Hazelnut", 0.2),
    ("Bread", 0.2),
    ("Puzzle", 0.2),
    ("Ice Pop", 0.2),
    ("Earth", 0.2),
    ("Cursor", 0.2),
    ("Rain Drop", 0.2),
    ("Fenrir", 0.2),
    ("Doghouse", 0.2),
    ("Cactus", 0.2),
    ("Guitar", 0.2),
    ("Doctor Hat", 0.2),
    ("Coin", 0.2),
    ("Pirate Scull", 0.2),
    ("Mountain Goat", 0.2),
    ("Leaf", 0.2),
    ("Kitsune", 0.2),
    ("Chick", 0.2),
    ("Handset", 0.2),
    ("Thor Hammer", 0.2),
    ("Onigiri", 0.2),
    ("Wizard Hat", 0.2),
    ("Hard Hat", 0.4),
    ("Illuminati", 0.4),
    ("Magic Vial", 0.4),
    ("Ram of Amun", 0.4),
    ("Cicada", 0.4),
    ("Mannaz Rune", 0.4),
    ("Coat of Arms", 0.4),
    ("Warhorse", 0.4),
    ("Moai Head", 0.4),
    ("Jewel", 0.4),
    ("Chili Pepper", 0.4),
    ("Sakura Flower", 0.4),
    ("Sakura", 0.4),
    ("Spider", 0.4),
    ("Oxen of Fire", 0.4),
    ("Elephant", 0.4),
    ("Khinkali", 0.4),
    ("Beanie", 0.4),
    ("Kashket", 0.4),
    ("Money Bag", 0.4),
    ("Like", 0.4),
    ("Eikthyrnir", 0.4),
    ("Anchor", 0.4),
    ("Wagasa", 0.4),
    ("Octopus", 0.4),
    ("Mafdet", 0.4),
    ("Flying Dragon", 0.4),
    ("Shield", 0.4),
    ("Hedgehog", 0.4),
    ("Lotus Flower", 0.4),
    ("Twin Peaks", 0.4),
    ("Wontons", 0.4),
    ("Rooster", 0.4),
    ("Venetian Mask", 0.4),
    ("Gold", 0.4),
    ("Moon Eagle", 0.4),
    ("Crescent", 0.4),
    ("Scorpion", 0.4),
    ("Spanner", 0.4),
    ("Dragonfly", 0.4),
    ("Horseshoe", 0.4),
    ("Bubble Tea", 0.4),
    ("Imperial Lion", 0.4),
    ("Heater Shield", 0.4),
    ("Kitsune Mask", 0.4),
    ("Jester Hat", 0.4),
    ("Viper", 0.4),
    ("Egg", 0.4),
    ("Phoenix", 0.4),
    ("Crusader Cross", 0.4),
    ("Garden Pot", 0.4),
    ("Owl", 0.4),
    ("Pearl", 0.4),
    ("Peaked Cap", 0.4),
    ("Flower Cross", 0.4),
    ("Alert Serpent", 0.4),
    ("Two Katanas", 0.4),
    ("Divine Falcon", 0.4),
    ("Jolly Roger", 0.4),
    ("Oculus", 0.4),
    ("Tree of Life", 0.4),
    ("Lion King", 0.4),
    ("Leprechaun", 0.4),
    ("Bearskin", 0.4),
    ("Nemes", 0.4),
    ("Tamagotchi", 0.4),
    ("Red Deer", 0.4),
    ("Tetsubin", 0.4),
    ("Royal Turban", 0.4),
    ("Monstera", 0.4),
    ("Baphomet", 0.4),
    ("Trinity Knot", 0.4),
    ("Sparks", 0.4),
    ("Flower Tulip", 0.4),
    ("Bandage", 0.4),
    ("Jörmungandr", 0.4),
    ("Diamond", 0.4),
    ("Legionary", 0.4),
    ("Glasses", 0.4),
    ("Ring", 0.4),
    ("Flower", 0.4),
    ("Kudu Totem", 0.4),
    ("Flower Sun", 0.5),
    ("Holy Grail", 0.5),
    ("Star Crown", 0.5),
    ("Gingerbread", 0.5),
    ("Cat Mask", 0.5),
    ("Shooting Star", 0.5),
    ("Planet", 0.5),
    ("Piggy Bank", 0.5),
    ("Old Candle", 0.5),
    ("Heart", 0.5),
    ("Polar Bear", 0.5),
    ("Greek Sun", 0.5),
    ("Crusader", 0.5),
    ("War Tiger", 0.5),
    ("Spellbook", 0.5),
    ("Elf Hat", 0.5),
    ("Mask", 0.5),
    ("Sushi Rolls", 0.5),
    ("Crab", 0.5),
    ("Griffon", 0.5),
    ("Egg Basket", 0.5),
    ("Viking Shield", 0.5),
    ("Coconut", 0.5),
    ("Snail", 0.5),
    ("Sun Lion", 0.5),
    ("Moon Face", 0.5),
    ("Top Hat", 0.5),
    ("Winged Helm", 0.5),
    ("Lion of Babylon", 0.5),
    ("Okami Wolf", 0.5),
    ("Love Lock", 0.5),
    ("Firebird", 0.5),
    ("Ushanka", 0.5),
    ("Brain", 0.5),
    ("Sea Dragon", 0.5),
    ("La Corona", 0.5),
    ("Crown", 0.5),
    ("Cocktail", 0.5),
    ("Knight", 0.5),
    ("Dagger", 0.5),
    ("Horned Helm", 0.5),
    ("Bike Helmet", 0.5),
    ("Gua Pi Mao", 0.5),
    ("Bone", 0.5),
    ("Arabian Horse", 0.5),
    ("Cavalier Hat", 0.5),
    ("Police Badge", 0.5),
    ("Novus Ordo", 0.5),
    ("Bunny Ears", 0.5),
    ("Full Moon", 0.5),
    ("Celtic Cross", 0.5),
    ("Doberman", 0.5),
    ("Maple", 0.5),
    ("Banner", 0.5),
    ("White Deer", 0.5),
    ("Paw Print", 0.5),
    ("High Heels", 0.5),
    ("Carambola", 0.5),
    ("Inca Sun", 0.5),
    ("Bascinet", 0.5),
    ("Flashlight", 0.5),
    ("Conical Hat", 0.5),
    ("Pomegranate", 0.5),
    ("Car", 0.5),
    ("Fried Egg", 0.5),
    ("Moon Cross", 0.5),
    ("Trophy", 0.5),
    ("Crystal", 0.5),
    ("Mining Helmet", 0.5),
    ("Aztec Totem", 0.5),
    ("Moto Helmet", 0.5),
    ("Sauron", 0.5),
    ("High Hat", 0.5),
    ("Piranha", 0.5),
    ("Shortsword", 0.5),
    ("Bull of Heaven", 0.5),
    ("Tribal Shield", 0.5),
    ("Musical Note", 0.5),
    ("Easter Bunny", 0.5),
    ("Thief", 0.5),
    ("Cheese", 0.5),
    ("Mustang", 0.5),
    ("Wolf Rage", 0.5),
    ("Geisha Fan", 0.5),
    ("Cow Skull", 0.5),
    ("Academic Cap", 0.5),
    ("Spring Chick", 0.5),
    ("Pilot Hat", 0.5),
    ("Hermit Shell", 0.5),
    ("Cowboy Hat", 0.5),
    ("Heraldic Lily", 0.5),
    ("Nemean Lion", 0.5),
    ("Croissant", 0.5),
    ("Champagne", 0.5),
    ("Plume Shako", 0.5),
    ("Scarab", 0.5),
    ("Moon", 0.5),
    ("Sharp Sword", 0.5),
    ("Obon Lantern", 0.5),
    ("Winged Helmet", 0.5),
    ("Silver Ibis", 0.5),
    ("Shark Knife", 0.5),
    ("Spirit Impala", 0.5),
    ("Hand of God", 0.5)
]
# === Создаём счётчики уже использованных атрибутов ===
used_models = Counter([gift[0] for gift in real_gifts])
used_backgrounds = Counter([gift[1] for gift in real_gifts])
used_patterns = Counter([gift[2] for gift in real_gifts])

# === Функция генерации с учётом уже использованных значений ===
def generate_adjusted_pool(attr_list, used_counter, total):
    pool = []
    remainders = []
    total_used = 0

    for name, percent in attr_list:
        exact = total * percent / 100
        allowed = max(0, math.floor(exact) - used_counter.get(name, 0))
        remainder = (exact - math.floor(exact)) if allowed > 0 else 0
        pool.extend([name] * allowed)
        remainders.append((remainder, name))
        total_used += allowed

    shortfall = (total - len(real_gifts)) - len(pool)
    remainders.sort(reverse=True)

    for i in range(shortfall):
        name = remainders[i % len(remainders)][1]
        pool.append(name)

    return pool

# === Генерация пулов ===
remaining = total_supply - len(real_gifts)
model_pool = generate_adjusted_pool(models, used_models, total_supply)
background_pool = generate_adjusted_pool(backgrounds, used_backgrounds, total_supply)
pattern_pool = generate_adjusted_pool(patterns, used_patterns, total_supply)

# === Перемешивание ===
random.shuffle(model_pool)
random.shuffle(background_pool)
random.shuffle(pattern_pool)

# === Создание новых подарков ===
new_gifts = list(zip(model_pool[:remaining], background_pool[:remaining], pattern_pool[:remaining]))

# === Объединяем с реальными ===
all_gifts = real_gifts + new_gifts
gifts_with_id = [(i + 1, *gift) for i, gift in enumerate(all_gifts)]

# === Сохраняем в CSV ===
with open("telegram_gifts_resumed.csv", "w", newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(["ID", "Model", "Background", "Pattern"])
    writer.writerows(gifts_with_id)

print(f"Сгенерировано {len(new_gifts)} подарков. Файл сохранён как 'telegram_gifts_resumed.csv'")
